-- SQL Questions and Queries --
-- 1. find number of businesses in each category.
WITH CTE AS (
SELECT BUSINESS_ID,
TRIM(A.VALUE) CATEGORY
FROM TBL_YELP_BUSINESSES
,LATERAL SPLIT_TO_TABLE(CATEGORIES,',') A
)
SELECT CATEGORY, COUNT(*) AS NUMBER_OF_BUSINESSES
FROM CTE
GROUP BY 1
ORDER BY 2 DESC;

-- 2. find the top 10 users who hae reviewed most businesses in the 'Restaurants' category --
SELECT R.USER_ID,
COUNT(DISTINCT R.BUSINESS_ID)
FROM TBL_YELP_REVIEWS R
INNER JOIN TBL_YELP_BUSINESSES B ON R.BUSINESS_ID = B.BUSINESS_ID
WHERE B.CATEGORIES ILIKE '%restaurant%'
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10;

-- 3. find the most popular categories of businesses based on the number of reviews --
WITH CTE AS (
SELECT BUSINESS_ID,
TRIM(A.VALUE) CATEGORY
FROM TBL_YELP_BUSINESSES
,LATERAL SPLIT_TO_TABLE(CATEGORIES,',') A
)
SELECT CATEGORY, COUNT(*) NO_OF_REVIEWS
FROM CTE
INNER JOIN TBL_YELP_REVIEWS R ON CTE.BUSINESS_ID = R.BUSINESS_ID
GROUP BY 1
ORDER BY 2 DESC;

-- 4. find the top 3 most recent reviews for each business --
WITH CTE AS (
SELECT R.*,
B.NAME,
ROW_NUMBER() OVER (PARTITION BY R.BUSINESS_ID ORDER BY REVIEW_DATE DESC ) RN
FROM TBL_YELP_REVIEWS R
INNER JOIN TBL_YELP_BUSINESSES B ON R.BUSINESS_ID = B.BUSINESS_ID
)
SELECT *
FROM CTE
WHERE RN <= 3;

-- 5. find the month with te highest number of reviews --
SELECT MONTH(REVIEW_DATE) AS REVIEW_MONTH,
COUNT(*) AS NUMBER_OF_REVIEWS
FROM TBL_YELP_REVIEWS
GROUP BY 1
ORDER BY 2 DESC;

-- 6. find the percentage of 5star reviews for each business --
SELECT B.BUSINESS_ID,
B.NAME,
COUNT(*) TOTAL_REVIEWS,
SUM(CASE WHEN R.REVIEW_STARS = 5 THEN 1 ELSE 0 END) STAR5_REVIEWS,
STAR5_REVIEWS*100/TOTAL_REVIEWS PERCENT_5_STAR
FROM TBL_YELP_REVIEWS R
INNER JOIN TBL_YELP_BUSINESSES B ON R.BUSINESS_ID = B.BUSINESS_ID
GROUP BY 1,2;

-- 7. find the top 5 most reviewed businesses in each city --
WITH CTE AS (
SELECT B.CITY,
B.BUSINESS_ID,
B.NAME,
COUNT(*) TOTAL_REVIEWS
FROM TBL_YELP_REVIEWS R
INNER JOIN TBL_YELP_BUSINESSES B ON R.BUSINESS_ID = B.BUSINESS_ID
GROUP BY 1,2,3
ORDER BY 1
)
SELECT *
FROM CTE
QUALIFY ROW_NUMBER() OVER(PARTITION BY CITY ORDER BY TOTAL_REVIEWS DESC) <= 5;

-- 8. find the average rating of businesses that have atleast 100 reviews --
SELECT B.BUSINESS_ID,
B.NAME,
COUNT(*) TOTAL_REVIEWS,
AVG(REVIEW_STARS) AVERAGE_RATING
FROM TBL_YELP_REVIEWS R
INNER JOIN TBL_YELP_BUSINESSES B ON R.BUSINESS_ID = B.BUSINESS_ID
GROUP BY 1,2
having TOTAL_REVIEWS >= 100;

-- 9. list the top 10 users who have written the most reviews, along with the business they reviewed --
WITH CTE AS (
SELECT R.USER_ID,
COUNT(*) TOTAL_REVIEWS
FROM TBL_YELP_REVIEWS R
INNER JOIN TBL_YELP_BUSINESSES B ON R.BUSINESS_ID = B.BUSINESS_ID
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10
)
SELECT USER_ID,
BUSINESS_ID
FROM TBL_YELP_REVIEWS
WHERE USER_ID IN (SELECT USER_ID FROM CTE)
GROUP BY 1,2
ORDER BY USER_ID;

-- 10. find the top 10 businesses with highest posiive sentiment reviews --
SELECT B.BUSINESS_ID,
B.NAME,
COUNT(*) TOTAL_REVIEWS
FROM TBL_YELP_REVIEWS R
INNER JOIN TBL_YELP_BUSINESSES B ON R.BUSINESS_ID = B.BUSINESS_ID
WHERE SENTIMENTS = 'Positive'
GROUP BY 1,2
ORDER BY 3 DESC
LIMIT 10;


--  --
SELECT *
FROM TBL_YELP_REVIEWS R
INNER JOIN TBL_YELP_BUSINESSES B ON R.BUSINESS_ID = B.BUSINESS_ID;





